name = "Banjo Tooie"
home = "https://discord.com/channels/731205301247803413/1135352499172286505"

[versions]
"1.8.1" = { url = "https://github.com/jjjj12212/Archipelago-BanjoTooie/releases/download/V1.8.1-beta/banjo_tooie.apworld" }
"1.9.0" = { url = "https://github.com/jjjj12212/Archipelago-BanjoTooie/releases/download/V1.9-beta/banjo_tooie.apworld" }
