name = "Bloons TD6"
home = "https://discord.com/channels/731205301247803413/1188559959508668527"
default_url = "https://github.com/GamingInfinite/Archipelago/releases/download/{{version}}.0/bloonstd6.apworld"
default_version = "disabled"

[versions]
"0.2.3" = {}
"0.3.3" = {}
