name = "Celeste"
home = "https://discord.com/channels/731205301247803413/1021069526625947729"
default_url = "https://github.com/doshyw/CelesteArchipelago/releases/download/{{version}}/celeste.apworld"

[versions]
"0.3.0" = {}
