name = "League of Legends"
home = "https://discord.com/channels/731205301247803413/1184691812099686492"
default_url = "https://github.com/gaithernOrg/LoLAP/releases/download/{{version}}/lol.apworld"

[versions]
"0.1.5" = {}
