name = "Manual: Beat Saber"
home = "https://discord.com/channels/1097532591650910289/1242883411845058580"

[versions]
"1.1.0" = { url = "https://github.com/spencer2585/Archipelago-Beatsaber-Manual/releases/download/1.1/manual_Beatsaber_Spencer2585.apworld" }
