name = "Monster Hunter Rise"
home = "https://discord.com/channels/731205301247803413/1059399228339802192"
default_url = "https://github.com/HillbillyDroid/MHRise-APWorld/releases/download/v{{version}}/mhrise.apworld"

[versions]
"0.1.1" = {}
