name = "osu!"
home = "https://discord.com/channels/731205301247803413/1195040661171355730"

[versions]
"1.0.0-beta" = { url = "https://github.com/lilymnky-F/Archipelago-Osu/releases/download/v1.0/osu.apworld" }
