name = "Outer Wilds"
home = "https://discord.com/channels/731205301247803413/1178700404637311086"
default_url = "https://github.com/Ixrec/OuterWildsArchipelagoRandomizer/releases/download/v{{version}}/outer_wilds.apworld"

[versions]
"0.2.4" = {}
