name = "Paper Mario 64"
home = "https://discord.com/channels/731205301247803413/1059875783071502398"
default_url = "https://github.com/JKBSunshine/PMR_APWorld/releases/download/v{{version}}/papermario.apworld"

[versions]
"0.4.0" = {}
