name = "Pokemon Black and White"
home = "https://discord.com/channels/731205301247803413/1414928022854696991"
default_url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/{{version}}/pokemon_bw_without_maps.apworld"
# NOTE: upstream flagged this world for code that steals items with
# "badge", "tm" or "hm" and places them with no logic in its own world.
# Enabled locally on this fork.

[versions]
"0.3.30" = { url = "https://github.com/BlastSlimey/PokemonBWAP/releases/download/0.3.30/pokemon_bw.apworld" }
"0.3.17" = {}
"0.3.14" = {}
"0.3.13" = {}
