name = "Pseudoregalia"
home = "https://discord.com/channels/731205301247803413/1147564210436452393"
default_url = "https://github.com/pseudoregalia-modding/pseudoregalia-archipelago/releases/download/{{version}}/pseudoregalia.apworld"

[versions]
"0.7.2" = {}
