name = "The Legend of Zelda: Oracle of Seasons"
home = "https://discord.com/channels/731205301247803413/1130706151303041054"

[versions]
"7.1.0" = { url = "https://github.com/Dinopony/ArchipelagoOoS/releases/download/oos-7.1/tloz_oos.apworld" }
