name = "The Legend of Zelda: The Wind Waker"
home = "https://discord.com/channels/731205301247803413/1080383306748678165"
# Wind waker download link is a zip containing the apworld, since I don't want to special case it, act as if it doesn't have a download link
# Releases are here: https://github.com/tanjo3/tww_apworld/releases


[versions]
"2.4.0" = { local = "../apworlds/tww-2.4.0.apworld" }
