name = "Wario Land 1"
home = "https://discord.com/channels/731205301247803413/1173641836502454303"
default_url = "https://github.com/randomcodegen/Archipelago_WL/releases/download/{{version}}/wl.apworld"

[versions]
"1.2.2" = {}

